In [8]:
import numpy as np

data1=[6,7.5,8,0.1]
type(data1)
arr1=np.array(data1)
type(arr1)
# 함수 array를 통해 list를 ndarray 객체로 만든다. - n차원의 선형적 구조

data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [10]:
arr2.dtype

<function ndarray.cumsum>

In [12]:
z=np.zeros(10)
type(z)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
z2=np.zeros((3,6))
z2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
z3=np.empty((2,3,2)) #높이, 행, 열
z3

array([[[6.67e-322, 0.00e+000],
        [0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000]],

       [[0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000]]])

In [16]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
data2=np.array(data2, dtype=np.float64)
int_data2=data2.astype(np.int64)

In [27]:
print(int_data2[0][3])
print(int_data2[0,3]) # 1행,4열의 값 탐색

4
4


## numpy - 색인

In [38]:
arr = np.arange(15).reshape(3,5)
print(arr)
arr[0,2]
arr[:2,1:]
arr[arr >= 5].reshape(2,5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## numpy - fancy indexing

In [6]:
a = np.zeros((8,3))
for i in range(8):
    a[i] = i
a
# 1행,4행, 5행만 읽어오세요
print(a)
print(a[[0,3,5]])
# 특정 행과 열을 불러오기
# a[[]] 앞에 뽑은 행 * [:,[원하는 열]]
print(a[[0,3,4,-1]][:,[1,2]])

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]]
[[0. 0. 0.]
 [3. 3. 3.]
 [5. 5. 5.]]
[[0. 0.]
 [3. 3.]
 [4. 4.]
 [7. 7.]]


In [12]:
# np.ix_() - 행과 열 뽑기
a[np.ix_([1,5,7,2],[0,2,1])]

array([[1., 1., 1.],
       [5., 5., 5.],
       [7., 7., 7.],
       [2., 2., 2.]])

In [13]:
arr = np.arange(15).reshape((3,5))

In [14]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [17]:
np.dot(arr,arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [18]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [19]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06]])

In [21]:
np.random.rand(10)

array([0.83263118, 0.16460091, 0.55381432, 0.50596959, 0.96214188,
       0.89959677, 0.17753926, 0.3404535 , 0.82879197, 0.96677406])

In [24]:
np.random.normal(0) # 정규분포화

-0.12132168029117295