## 1. np.ravel(x, order=' ') -> 2차원 배열을 1차원 벡터로 나열

In [2]:
import numpy as np

In [10]:
X = np.arange(12).reshape(3,4)

In [8]:
np.ravel(X,order='C') # 행을 기준으로 나열

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
np.ravel(X,order='F') # 열을 기준으로 나열

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

## 2. x.reshape(-1, 정수) / x.reshape(정수,-1) -> 행/열 기준으로 벡터로 나열

In [12]:
X.reshape(-1,1) # 1열로 나열
X.reshape(-1,2) # 2열로 나열

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [13]:
X.reshape(1,-1) # 1행으로 나열
X.reshape(2,-1) # 2행으로 나열

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

## 3. np.abs(x) -> 절대값 / count() -> 갯수 / any(1) 한개의 값씩 추출

## 4. np.isnan(x) -> 배열에 nan 포함 여부 확인 함수

In [14]:
a = np.array([0,1,2,np.nan,4])

In [15]:
np.isnan(a)

array([False, False, False,  True, False])

## 5. np.sqrt(x) - 제곱근 / np.square(x) - 제곱값 / np.sign(x) - 부호 판별

In [16]:
 y = np.array([1, 4, 100])

In [17]:
np.sqrt(y)

array([ 1.,  2., 10.])

In [19]:
np.square(y)

array([    1,    16, 10000], dtype=int32)

In [20]:
np.sign(y) # 양수(1) ,음수(-1), 0(zero)

array([1, 1, 1])

## 6. np.prod(x) - 배열간 곱

In [22]:
b = np.array([[1,2],[3,4]])

In [23]:
np.prod(b)

24

In [25]:
np.prod(b,axis=0) # 열기준 계산

array([3, 8])

In [26]:
np.prod(b,axis=1) # 행기준 계산

array([ 2, 12])

## 7. np.sum() - 배열간 합

In [27]:
np.sum(b)

10

In [28]:
np.sum(b,axis=0)

array([4, 6])

In [29]:
np.sum(b,axis=1)

array([3, 7])

## 8. np.diff() - 배열 원소간 차분 

In [30]:
np.diff(b)

array([[1],
       [1]])

In [31]:
np.diff(b, axis=0)

array([[2, 2]])

In [32]:
np.diff(b, axis=1)

array([[1],
       [1]])

## 9. np.round(a, N) a를 N자리까지 반올림

In [33]:
c = np.array([1.25,2.23424])

In [34]:
np.round(c,2)

array([1.25, 2.23])

## 10. np.ix_( , ) - fancy indexing

In [36]:
d = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

In [37]:
d_copy = np.ix_([0,3],[0,2])

In [38]:
d_copy

(array([[0],
        [3]]), array([[0, 2]]))

In [39]:
e = np.array(['a','b','c','d'])

In [40]:
e == 'a'

array([ True, False, False, False])

In [41]:
e != 'a'

array([False,  True,  True,  True])

In [43]:
e[e=='a'] == 1

C:\Users\acorn\AppData\Local\conda\conda\envs\xgboost\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.


False

## 11. df.sort_values() - 데이터 정렬

In [48]:
#!pip install pandas
import pandas as pd

In [51]:
df = pd.DataFrame({'sequence': [1, 3, 2],
                             'name': ['park', 'lee', 'choi'],
                             'age': [30, 20, 40]})


In [54]:
df.sort_values(by=['sequence'],axis=0) # by = 기준컬럼 #axis = 기준 행렬 정의

age  name  sequence
0   30  park         1
2   40  choi         2
1   20   lee         3

In [55]:
df.sort_values(by=['sequence'],axis=0, ascending=False) # 내림차순 

age  name  sequence
1   20   lee         3
2   40  choi         2
0   30  park         1

## 리스트 정렬 - sorted(list)

## 12. 교차표만들기 : pd.crosstab(index, columns)

In [57]:
from pandas import DataFrame
data = DataFrame({'id': ['id1', 'id1', 'id1', 'id2', 'id2', 'id3'],
                  'fac_1': ['a', 'a', 'a', 'b', 'b', 'b'],
                  'fac_2': ['d', 'd', 'd', 'c', 'c', 'd']})


In [59]:
pd.crosstab(data.fac_1,data.fac_2,margins=True)

fac_2  c  d  All
fac_1           
a      0  3    3
b      2  1    3
All    2  4    6

## pd.melt(data, id_vars=['id1', 'id2', ...]) / stack/unstack

## 13. pd.pivot_table(data, index, columns, values, aggfunc)


In [61]:
data = DataFrame({'cust_id': ['c1', 'c1', 'c1', 'c2', 'c2', 'c2', 'c3', 'c3', 'c3'],
                  'prod_cd': ['p1', 'p2', 'p3', 'p1', 'p2', 'p3', 'p1', 'p2', 'p3'],
                  'grade' : ['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B'],
                  'pch_amt': [30, 10, 0, 40, 15, 30, 0, 0, 10]})


In [64]:
pd.pivot_table(data,index='cust_id',columns='prod_cd',
               values='pch_amt',aggfunc=np.sum,
               margins=True)

prod_cd  p1  p2  p3  All
cust_id                 
c1       30  10   0   40
c2       40  15  30   85
c3        0   0  10   10
All      70  25  40  135

In [65]:
pd.pivot_table(data,index='cust_id',columns='prod_cd',
               values='pch_amt',aggfunc=np.mean,
               margins=True)

prod_cd  p1  p2  p3        All
cust_id                       
c1       30  10   0  13.333333
c2       40  15  30  28.333333
c3        0   0  10   3.333333
All      23   8  13  15.000000

## 14. 연속형 변수의 이산형화(1) - np.linspace/np.digitize

In [75]:
np.random.seed(10)


# making DataFrame with continuous values

df = DataFrame({'C1': np.random.randn(20),
                'C2': ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a','b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b']})

bins = np.linspace(df.C1.min(), df.C1.max(),10)
df['C1_bin']=np.digitize(df['C1'], bins)
df.head()

C1 C2  C1_bin
0  1.331587  a       9
1  0.715279  a       7
2 -1.545400  a       1
3 -0.008384  a       5
4  0.621336  a       7

## 14. 연속형 변수의 이산형화(2) - pd.get_dummies()

In [78]:
pd.get_dummies(df['C1_bin'],prefix='C1',drop_first=True)

C1_2  C1_3  C1_5  C1_6  C1_7  C1_8  C1_9  C1_10
0      0     0     0     0     0     0     1      0
1      0     0     0     0     1     0     0      0
2      0     0     0     0     0     0     0      0
3      0     0     1     0     0     0     0      0
4      0     0     0     0     1     0     0      0
5      0     1     0     0     0     0     0      0
6      0     0     0     1     0     0     0      0
7      0     0     1     0     0     0     0      0
8      0     0     1     0     0     0     0      0
9      0     0     1     0     0     0     0      0
10     0     0     0     1     0     0     0      0
11     0     0     0     0     0     0     1      0
12     1     0     0     0     0     0     0      0
13     0     0     0     0     0     1     0      0
14     0     0     0     1     0     0     0      0
15     0     0     0     1     0     0     0      0
16     1     0     0     0     0     0     0      0
17     0     0     1     0     0     0     0      0
18     0     0     0     0     0     0     0      1
19     1     0     0     0     0     0     0      0

## 14. 연속형 변수의 이산형화(3) - np.where()

In [80]:
df['high_low'] = np.where(df['C1']>=df.C1.mean(),'high','low')
df['high_low'].head()

0    high
1    high
2     low
3     low
4    high
Name: high_low, dtype: object

In [81]:
Q1 = np.percentile(df['C1'],25)
Q2 = np.percentile(df['C1'],75)

df['h_m_l'] = np.where(df['C1']>=Q2, '01_high',
                      np.where(df['C1']>=Q1, '02_medium','03_low'))

## 15. OneHotEncoder() - 범주형 변수의 이항변수화

In [83]:
from sklearn.preprocessing import OneHotEncoder



data_train = np.array([[0, 0, 0],[0, 1, 1],
                               [0, 2, 2],[1, 0, 3],
                               [1, 1, 4]])

enc = OneHotEncoder()
enc.fit(data_train)

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [86]:
data_new=np.array([[1,2,4]])
enc.transform(data_new).toarray()

array([[0., 1., 0., 0., 1., 0., 0., 0., 0., 1.]])

## 16. sklearn.preprocessing.minmax_scale() 함수를 사용한 최소.최대 '0~1' 범위 변환


In [89]:
In [16]: from sklearn.preprocessing import minmax_scale

 

# scaling X to min~max '0~1' range
X = np.array([[ 10, -10, 1],
                [ 5, 0, 2],
                [ 0, 10, 3]])



X_MinMax_scaled = minmax_scale(X, axis=0, copy=True)

X_MinMax_scaled


C:\Users\acorn\AppData\Local\conda\conda\envs\xgboost\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64.
  warnings.warn(msg, DataConversionWarning)


array([[1. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [0. , 1. , 1. ]])

## 17. StandardScaler/RobustScaler()

In [90]:
StandardScaler().fit_transform(x)

RobustScaler().fit_transform(x)

# 2번째 것이 더 유용


NameError: name 'StandardScaler' is not defined

## 18. 유일한 값 찾기 - unique/value_counts()

## 19. 결측값 관리(교체,제거)

In [2]:
# 중복값 여부 확인
df.duplicated()
# 특정 칼럼 값 교체
df.replace({'C1':np.nan},{'C1':10})
df.replace({'C1':'a'},{'C1':'b'})
# 결측값이 있는 행.열 제거
df.dropna(axis=0 or 1)
# 결측값을 특정 값으로 채우기
df.fillna(0)
df.fillna('string')
# 결측값 존재 여부
df.isnull()
df.notnull()

df.isnull().sum()

NameError: name 'df' is not defined

## 20. join - pd.merge() / pd.concat()

In [ ]:
pd.merge(df1,df2, left_index=True,right_index=True,how=' ')
# how = 'inner,outer,left,right'



pd.concat([df1,df2],axis = 0 or 1, join = 'outer,inner')

## 21. 정규화 vs 표준화

In [ ]:
from sklearn.preprocessing import minmax_scale, StandardScaler, MinMaxScaler
df['A'].apply(minmax_scale) # 단독 적용

minmax_scale = MinMaxScaler(feature_range[0,1]).fit(df[['A','B']])
df_minmax = minmax_scale.transfrom(df[['A','B']])


##################################################################

df['A'].apply(lambda x: StandardScaler(x)) # 단독 적용

std_scale = StandardScaler().fit(df[['A','B']])
df_std = std_scale.transfrom(df[['A','B']])

## 22. 연속형 데이터의 구간 범주화

In [ ]:
bins = [0,25,50,75,100]
bins_names = ['A','B','C','D','E']
cataegories = pd.cut(df['score'], bins, label=bins_names)