In [1]:
import tensorflow as tf

hello = tf.constant('Hello, TensorFlow!')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [2]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [3]:
sess = tf.Session()
print(sess.run(hello))
print(sess.run([a,b,c]))

b'Hello, TensorFlow!'
[10, 32, 42]


In [4]:
sess.close()

In [5]:
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [6]:
x_data = [[1,2,3],[4,5,6]]

In [7]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

In [8]:
expr = tf.matmul(X, W) + b

In [9]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [10]:
print(x_data)

[[1, 2, 3], [4, 5, 6]]


In [11]:
print(sess.run(W))

[[-1.420252    0.10717922]
 [-1.2534639   1.1835194 ]
 [-1.004744   -0.12426467]]


In [12]:
print(sess.run(b))

[[-0.6652669]
 [ 1.7500612]]


In [14]:
print(sess.run(expr,feed_dict={X:x_data}))

[[ -7.606679    1.4361569]
 [-16.22673     7.350786 ]]


In [15]:
sess.close()

In [16]:
# 기초적인 선형 회귀 모델

In [17]:
x_data = [1,2,3]
y_data = [1,2,3]

W = tf.Variable(tf.random_uniform([1],-1.0,1.0))
b = tf.Variable(tf.random_uniform([1],-1.0,1.0))

X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")
print(X)
print(Y)

Tensor("X:0", dtype=float32)
Tensor("Y:0", dtype=float32)


In [20]:
hypothesis = W*X + b

In [21]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))

In [22]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)

In [23]:
train_op=optimizer.minimize(cost)

In [26]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})

        print(step, cost_val, sess.run(W), sess.run(b))

    # 최적화가 완료된 모델에 테스트 값을 넣고 결과가 잘 나오는지 확인해봅니다.
    print("\n=== Test ===")
    print("X: 5, Y:", sess.run(hypothesis, feed_dict={X: 5}))
    print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))

0 4.6258836 [1.1717954] [-0.14278534]
1 0.059998583 [1.0685672] [-0.18294643]
2 0.005233053 [1.0777497] [-0.17378399]
3 0.0043643387 [1.0746969] [-0.17012708]
4 0.0041496134 [1.0730307] [-0.16598041]
5 0.003952425 [1.0712608] [-0.16199662]
6 0.0037646724 [1.0695494] [-0.15810162]
7 0.003585851 [1.0678773] [-0.15430108]
8 0.0034155184 [1.0662456] [-0.15059178]
9 0.0032532811 [1.064653] [-0.14697164]
10 0.0030987517 [1.0630989] [-0.14343853]
11 0.0029515552 [1.061582] [-0.13999039]
12 0.002811353 [1.0601016] [-0.1366251]
13 0.002677819 [1.0586568] [-0.13334075]
14 0.0025506155 [1.0572467] [-0.13013533]
15 0.0024294585 [1.0558705] [-0.12700695]
16 0.0023140572 [1.0545275] [-0.12395376]
17 0.0022041379 [1.0532167] [-0.120974]
18 0.0020994397 [1.0519373] [-0.11806587]
19 0.0019997165 [1.0506889] [-0.11522764]
20 0.0019047293 [1.0494703] [-0.11245766]
21 0.0018142449 [1.0482811] [-0.10975423]
22 0.0017280662 [1.0471205] [-0.10711581]
23 0.0016459859 [1.0459877] [-0.10454082]
24 0.0015678052 