In [5]:
import pandas as pd
import numpy as np

In [2]:
raw_cat = pd.Categorical(["a","b","c","a"], categories=["b","c","d"],ordered=False)

In [3]:
raw_cat

[NaN, b, c, NaN]
Categories (3, object): [b, c, d]

In [6]:
df = pd.DataFrame({'A': range(1, 11), 'B': np.random.randn(10)})

In [7]:
df

A         B
0   1  0.626025
1   2  1.497767
2   3 -0.386011
3   4 -0.157710
4   5 -1.020755
5   6  1.968580
6   7 -0.870020
7   8  1.741458
8   9  1.746362
9  10 -1.519417

In [8]:
df.assign(ln_A = lambda x: np.log(x.A))

A         B      ln_A
0   1  0.626025  0.000000
1   2  1.497767  0.693147
2   3 -0.386011  1.098612
3   4 -0.157710  1.386294
4   5 -1.020755  1.609438
5   6  1.968580  1.791759
6   7 -0.870020  1.945910
7   8  1.741458  2.079442
8   9  1.746362  2.197225
9  10 -1.519417  2.302585

In [9]:
from numpy.random import randn
from pandas import DataFrame
df = pd.DataFrame(randn(10, 2), columns=list('ab'))
print(df.query('a > b'))
print(df[df.a > df.b]) 

          a         b
1  1.482028  0.513923
2  1.361653 -1.092469
3 -0.466280 -0.781375
4  1.275060  1.122929
6 -1.621406 -3.127233
7  1.085844 -0.305079
9  0.275737 -0.973958
          a         b
1  1.482028  0.513923
2  1.361653 -1.092469
3 -0.466280 -0.781375
4  1.275060  1.122929
6 -1.621406 -3.127233
7  1.085844 -0.305079
9  0.275737 -0.973958


In [10]:
x = 1
y = 2

In [12]:
np.array([x, y])

array([1, 2])

In [28]:
# 실습에 필요한 라이브러리를 불러옵니다.
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
# x, y, beta_0, beta_1 을 이용해 loss 값을 계산합니다. 
beta_0 = 1
beta_1 = 0.5

#loss(x, y, beta_0, beta_1):

print(x)
y = np.array(y)
m = y.size
J = 0
theta=np.array([beta_0, beta_1])
h = x.dot(theta)
J = (np.sum(np.square(h-y)/(2*m)))   
# 실습에 사용되는 데이터입니다.
x = [8.70153760, 3.90825773, 1.89362433, 3.28730045, 7.39333004, 2.98984649, 2.25757240, 9.84450732, 9.94589513, 5.48321616]
y = [5.64413093, 3.75876583, 3.87233310, 4.40990425, 6.43845020, 4.02827829, 2.26105955, 7.15768995, 6.29097441, 5.19692852]


[8.7015376  3.90825773 1.89362433 3.28730045 7.39333004 2.98984649
 2.2575724  9.84450732 9.94589513 5.48321616]


ValueError: shapes (10,) and (2,) not aligned: 10 (dim 0) != 2 (dim 0)

In [30]:
x

array([8.7015376 , 3.90825773, 1.89362433, 3.28730045, 7.39333004,
       2.98984649, 2.2575724 , 9.84450732, 9.94589513, 5.48321616])

In [48]:
y=y.reshape(y.size,1)
theta1=np.array([beta_0, beta_1])
theta1
theta1=theta1.reshape(theta.size,1)
theta1

array([[1. ],
       [0.5]])

In [33]:
y

array([[5.64413093],
       [3.75876583],
       [3.8723331 ],
       [4.40990425],
       [6.4384502 ],
       [4.02827829],
       [2.26105955],
       [7.15768995],
       [6.29097441],
       [5.19692852]])

In [60]:
m=y.size
J =0
h = X.dot(theta1)
X=np.c_[np.ones(x.shape[0]),x]
J=(np.sum(np.square(h-y)/(2*m)))
J

0.8354338583500373

In [41]:
theta=np.array([[0],[0]])
theta

array([[0],
       [0]])

In [63]:
x1 = [8.70153760, 3.90825773, 1.89362433, 3.28730045, 7.39333004, 2.98984649, 2.25757240, 9.84450732, 9.94589513, 5.48321616]
y1 = [5.64413093, 3.75876583, 3.87233310, 4.40990425, 6.43845020, 4.02827829, 2.26105955, 7.15768995, 6.29097441, 5.19692852]
y1 = np.array(y1)
y = y1.reshape(y.size,1)
print(x)
print(y)

[8.7015376  3.90825773 1.89362433 3.28730045 7.39333004 2.98984649
 2.2575724  9.84450732 9.94589513 5.48321616]
[[5.64413093]
 [3.75876583]
 [3.8723331 ]
 [4.40990425]
 [6.4384502 ]
 [4.02827829]
 [2.26105955]
 [7.15768995]
 [6.29097441]
 [5.19692852]]


In [66]:
x1 = np.array(x1)
X = np.c_[np.ones(x1.shape[0]), x1]
print(X)
beta_0 = 1
beta_1 = 0.5
theta = np.array([[1],[0.5]])

[[1.         8.7015376 ]
 [1.         3.90825773]
 [1.         1.89362433]
 [1.         3.28730045]
 [1.         7.39333004]
 [1.         2.98984649]
 [1.         2.2575724 ]
 [1.         9.84450732]
 [1.         9.94589513]
 [1.         5.48321616]]


In [76]:
theta1 = np.array(beta_0, beta_1)
    theta1 = theta1.T
def Costfunction (X, y, theta=theta): 
    m = y.size #n
    J = 0 # cost
    h = X.dot(theta) # X0*W0 + X1*W1 부분 : (100*K) x ( K*1)  ==> 100 *1 
    J = (np.sum(np.square(y-(h+1))) # Cost fuction 을 설정합니다. 
    
    return(J)
J

SyntaxError: invalid syntax (<ipython-input-76-175a81344c5f>, line 7)

In [94]:
theta1 = np.array([[beta_0], [beta_1]])
beta_01=theta1[1]
beta_00=theta1[0]
beta_01
theta_=np.vstack([beta_00, beta_01])
theta_
#theta1 = theta1.T

array([[1. ],
       [0.5]])

In [82]:
theta1[0]

array([1.])