In [15]:
import pandas as pd
df=pd.read_csv('정규화안된cj40개변수추출.csv',engine='python')
df.head()

Unnamed: 0   high    low        gdp   volume    pound   open  averwind  \
0           0  49700  49700  1151707.8     4422  1782.91  49700       1.4   
1           1  42250  42250  1151707.8     5043  1776.46  42250       2.0   
2           2  39400  35950  1151707.8  2102612  1763.38  36300       1.8   
3           3  37700  33650  1151707.8  2024290  1792.43  35100       1.8   
4           4  35750  33000  1151707.8   780230  1770.50  35700       2.2   

      h  Nikkei225  ...    dust  windtotal  hello1  hello5  maxatthatwindtime  \
0  4.02    9498.49  ...    55.8       1875  1003.6    1539               2004   
1  4.04    9539.45  ...    65.3       1690  1012.9    2400               1600   
2  4.08    9381.60  ...    84.3       1218  1015.1    1436               1231   
3  4.10    9376.48  ...    44.9       1738  1013.6    1445                858   
4  4.05    9426.71  ...    22.2       1566  1011.0    1632               1356   

   Kospi_종가  Kosdaq종가  mean_종가  averhumid  close  
0   1899.76    504.59   968.30       47.1  49700  
1   1902.29    509.59   954.13       58.1  42250  
2   1875.42    516.19   947.42       71.3  35950  
3   1857.32    514.59   951.85       64.5  35300  
4   1870.44    520.21   959.72       59.3  33400  

[5 rows x 45 columns]

In [16]:
del df['Unnamed: 0']
df.head()

high    low        gdp   volume    pound   open  averwind     h  \
0  49700  49700  1151707.8     4422  1782.91  49700       1.4  4.02   
1  42250  42250  1151707.8     5043  1776.46  42250       2.0  4.04   
2  39400  35950  1151707.8  2102612  1763.38  36300       1.8  4.08   
3  37700  33650  1151707.8  2024290  1792.43  35100       1.8  4.10   
4  35750  33000  1151707.8   780230  1770.50  35700       2.2  4.05   

   Nikkei225  FTSE100  ...    dust  windtotal  hello1  hello5  \
0    9498.49  5742.52  ...    55.8       1875  1003.6    1539   
1    9539.45  5703.89  ...    65.3       1690  1012.9    2400   
2    9381.60  5728.93  ...    84.3       1218  1015.1    1436   
3    9376.48  5757.86  ...    44.9       1738  1013.6    1445   
4    9426.71  5741.37  ...    22.2       1566  1011.0    1632   

   maxatthatwindtime  Kospi_종가  Kosdaq종가  mean_종가  averhumid  close  
0               2004   1899.76    504.59   968.30       47.1  49700  
1               1600   1902.29    509.59   954.13       58.1  42250  
2               1231   1875.42    516.19   947.42       71.3  35950  
3                858   1857.32    514.59   951.85       64.5  35300  
4               1356   1870.44    520.21   959.72       59.3  33400  

[5 rows x 44 columns]

In [17]:
df['yn']=df['close'] - df['beforeclose']
df.head()

high    low        gdp   volume    pound   open  averwind     h  \
0  49700  49700  1151707.8     4422  1782.91  49700       1.4  4.02   
1  42250  42250  1151707.8     5043  1776.46  42250       2.0  4.04   
2  39400  35950  1151707.8  2102612  1763.38  36300       1.8  4.08   
3  37700  33650  1151707.8  2024290  1792.43  35100       1.8  4.10   
4  35750  33000  1151707.8   780230  1770.50  35700       2.2  4.05   

   Nikkei225  FTSE100  ...   windtotal  hello1  hello5  maxatthatwindtime  \
0    9498.49  5742.52  ...        1875  1003.6    1539               2004   
1    9539.45  5703.89  ...        1690  1012.9    2400               1600   
2    9381.60  5728.93  ...        1218  1015.1    1436               1231   
3    9376.48  5757.86  ...        1738  1013.6    1445                858   
4    9426.71  5741.37  ...        1566  1011.0    1632               1356   

   Kospi_종가  Kosdaq종가  mean_종가  averhumid  close    yn  
0   1899.76    504.59   968.30       47.1  49700 -8700  
1   1902.29    509.59   954.13       58.1  42250 -7450  
2   1875.42    516.19   947.42       71.3  35950 -6300  
3   1857.32    514.59   951.85       64.5  35300  -650  
4   1870.44    520.21   959.72       59.3  33400 -1900  

[5 rows x 45 columns]

In [18]:
df.drop(['close'], inplace=True, axis=1)

In [19]:
def stockflow(x):
    if x >= 0:
        return '상승'
    else:
        return '하락'
df['yn'] = df.yn.map(lambda x: stockflow(x))
df.head()

high    low        gdp   volume    pound   open  averwind     h  \
0  49700  49700  1151707.8     4422  1782.91  49700       1.4  4.02   
1  42250  42250  1151707.8     5043  1776.46  42250       2.0  4.04   
2  39400  35950  1151707.8  2102612  1763.38  36300       1.8  4.08   
3  37700  33650  1151707.8  2024290  1792.43  35100       1.8  4.10   
4  35750  33000  1151707.8   780230  1770.50  35700       2.2  4.05   

   Nikkei225  FTSE100 ...  dust  windtotal  hello1  hello5  maxatthatwindtime  \
0    9498.49  5742.52 ...  55.8       1875  1003.6    1539               2004   
1    9539.45  5703.89 ...  65.3       1690  1012.9    2400               1600   
2    9381.60  5728.93 ...  84.3       1218  1015.1    1436               1231   
3    9376.48  5757.86 ...  44.9       1738  1013.6    1445                858   
4    9426.71  5741.37 ...  22.2       1566  1011.0    1632               1356   

   Kospi_종가  Kosdaq종가  mean_종가  averhumid  yn  
0   1899.76    504.59   968.30       47.1  하락  
1   1902.29    509.59   954.13       58.1  하락  
2   1875.42    516.19   947.42       71.3  하락  
3   1857.32    514.59   951.85       64.5  하락  
4   1870.44    520.21   959.72       59.3  하락  

[5 rows x 44 columns]

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(df['yn'])
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [ ]:
df["등락유무변환"] = df[""].map({"상승":1,"하락":0})
df.head()

In [12]:
df.iloc[:,0:43]

high    low        gdp   volume    pound   open  averwind      h  \
0     49700  49700  1151707.8     4422  1782.91  49700       1.4  4.020   
1     42250  42250  1151707.8     5043  1776.46  42250       2.0  4.040   
2     39400  35950  1151707.8  2102612  1763.38  36300       1.8  4.080   
3     37700  33650  1151707.8  2024290  1792.43  35100       1.8  4.100   
4     35750  33000  1151707.8   780230  1770.50  35700       2.2  4.050   
5     34500  33250  1151707.8   520214  1771.11  33750       4.7  4.090   
6     34550  32300  1151707.8   681252  1754.23  34250       3.4  4.050   
7     32900  31100  1151707.8   540476  1771.11  32850       2.1  4.080   
8     33200  31350  1151707.8   501813  1776.49  31500       1.9  4.010   
9     32900  31250  1151707.8   423862  1796.93  31800       1.9  4.030   
10    32200  30400  1151707.8   326792  1804.00  31650       3.1  4.120   
11    31350  30000  1151707.8   394250  1793.87  31000       3.8  4.160   
12    31500  29950  1151707.8   358495  1787.85  31100       2.1  4.180   
13    30050  28900  1151707.8   325856  1788.25  29750       2.4  4.250   
14    29950  28200  1151707.8   427895  1801.20  29200       2.0  4.350   
15    30300  28400  1151707.8   444667  1790.06  28600       5.3  4.320   
16    31000  29650  1151707.8   221773  1796.77  30600       5.3  4.340   
17    31050  29750  1151707.8   143053  1783.10  30200       1.9  4.290   
18    29800  28700  1151707.8   155230  1795.14  28700       4.2  4.270   
19    29150  27050  1151707.8   229408  1785.51  28850       3.4  4.250   
20    29250  27800  1151707.8   217412  1806.43  27900       2.9  4.260   
21    30550  29150  1151707.8   259737  1812.14  29500       2.6  4.140   
22    30550  30550  1151707.8        0  1792.89  30550       2.0  4.150   
23    35100  35100  1151707.8    81093  1811.81  35100       1.8  4.140   
24    39600  36200  1151707.8  1587147  1827.65  36400       1.9  4.130   
25    37900  35750  1151707.8   459122  1810.10  37150       3.8  4.170   
26    36650  34350  1151707.8   348384  1797.89  36650       1.9  4.210   
27    34300  32600  1151707.8   311438  1790.67  33350       1.8  4.150   
28    34850  33500  1151707.8   209543  1813.48  34400       3.2  4.120   
29    34700  33000  1151707.8   217287  1804.32  34000       2.4  4.120   
...     ...    ...        ...      ...      ...    ...       ...    ...   
1866  89400  87600  1730398.5   164660  1465.32  89000       2.3  2.881   
1867  89800  88200  1730398.5   108317  1453.75  88800       1.8  2.891   
1868  90000  88300  1730398.5    96362  1447.74  90000       1.4  2.909   
1869  88700  87500  1730398.5   126444  1446.52  88700       1.1  2.912   
1870  88700  87100  1730398.5    77653  1448.22  87500       1.9  2.892   
1871  88700  87600  1730398.5    61135  1461.53  88200       1.4  2.872   
1872  89500  88000  1730398.5    67815  1458.73  88800       1.3  2.844   
1873  89600  88000  1730398.5    63603  1455.46  89100       1.4  2.863   
1874  88900  87400  1730398.5    76012  1456.25  88200       2.5  2.850   
1875  89900  88100  1730398.5   103154  1440.90  88100       2.2  2.818   
1876  91600  88500  1730398.5   186441  1444.91  88500       1.8  2.823   
1877  90700  87900  1730398.5   178781  1435.59  90100       1.6  2.829   
1878  91300  88000  1730398.5   194795  1428.64  89100       1.8  2.813   
1879  92500  89400  1730398.5   316320  1426.85  90300       1.9  2.817   
1880  92500  90500  1730398.5   178929  1436.51  92200       1.9  2.816   
1881  91500  90100  1730398.5    95850  1430.97  91000       1.9  2.814   
1882  91500  90000  1730398.5   110618  1436.89  90500       1.9  2.834   
1883  92600  90200  1730398.5   165618  1425.85  90200       1.7  2.827   
1884  91800  89500  1730398.5   165378  1435.19  91500       2.0  2.842   
1885  91200  89800  1730398.5    62528  1433.34  90300       2.1  2.818   
1886  91400  90400  1730398.5    79282  1439.27  90500       1.4  2.833   
1887  90600  89500  1730398.5   

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:43], df["yn"], test_size=0.33, random_state=42)

In [22]:
import pandas
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

seed = 7
model = LogisticRegression().fit(X_train, y_train)

predicted = model.predict(X_test)
report = classification_report(y_test, predicted)
print(report)
matrix = confusion_matrix(y_test, predicted)
print(matrix)

             precision    recall  f1-score   support

         상승       0.84      0.85      0.84       328
         하락       0.84      0.82      0.83       298

avg / total       0.84      0.84      0.84       626

[[280  48]
 [ 55 243]]


In [10]:
a=pd.DataFrame(list(X_test.iloc[1,:]))
b=a.T

In [11]:
#a=list([5.825913,-1.294833,-0.730723])
model.predict(b)

array([0], dtype=int64)

pc1       pc2       pc3     close
0    -8.076955 -4.332277 -7.047220 -0.974593
1    -8.013912 -4.470804 -7.005688 -0.977764
2    -8.006509 -4.515060 -6.972148 -0.982520
3    -7.795684 -4.518484 -6.930466 -0.987277
4    -7.711748 -4.799284 -6.832768 -0.993618
5    -7.654417 -4.919061 -6.784022 -0.990447
6    -7.557367 -4.983991 -6.730631 -0.988862
7    -7.409448 -5.087126 -6.681922 -0.984106
8    -7.342716 -5.143531 -6.594702 -0.998374
9    -7.401306 -5.321472 -6.609845 -0.988862
10   -7.266494 -5.290721 -6.558619 -0.982520
11   -7.206541 -5.311598 -6.499400 -0.987277
12   -7.218656 -5.292112 -6.511370 -0.995204
13   -7.320143 -5.141982 -6.556466 -0.996789
14   -7.263473 -5.133394 -6.524091 -0.979350
15   -7.265249 -5.199208 -6.530555 -0.984106
16   -7.184006 -5.178355 -6.462469 -0.980935
17   -7.188520 -5.335917 -6.433696 -0.985691
18   -7.009819 -5.379576 -5.268778 -0.982520
19   -7.063324 -5.289298 -5.255334 -0.987277
20   -7.014371 -5.292668 -5.232298 -0.987277
21   -6.984467 -5.353756 -5.192453 -0.993618
22   -6.993107 -5.175175 -5.203250 -0.988862
23   -6.905810 -5.247276 -5.152870 -0.990447
24   -6.859810 -5.327160 -5.131031 -1.006301
25   -6.822667 -5.473029 -5.128510 -1.011058
26   -6.695660 -5.447327 -5.066030 -1.006301
27   -6.590729 -5.563797 -5.035370 -1.025326
28   -6.510929 -5.771331 -4.978384 -1.011058
29   -6.594985 -5.746497 -4.963119 -1.023741
...        ...       ...       ...       ...
2313  6.587209  0.625727  0.012249  0.964355
2314  6.487272  0.631309 -0.014351  0.958013
2315  6.517806  0.646833 -0.003893  0.935818
2316  6.520349  0.620973  0.009595  0.942159
2317  6.545051  0.651869  0.025649  0.958013
2318  6.545144  0.679142  0.021467  0.961184
2319  6.536440  0.627427  0.014413  1.078504
2320  6.592440  0.533744  0.007608  1.056308
2321  6.628014  0.604037  0.003333  1.078504
2322  6.667528  0.588465  0.020132  1.075333
2323  6.681253  0.637817  0.022389  1.043625
2324  6.661373  0.647080  0.020322  1.040454
2325  6.652743  0.677344  0.019089  0.996063
2326  6.613715  0.657049  0.013381  1.062650
2327  6.677021  0.664219  0.028787  1.072162
2328  6.670241  0.638609  0.008725  1.078504
2329  6.553240  0.350158 -0.549213  1.160945
2330  6.657457  0.067841 -0.531551  1.309973
2331  6.810934 -0.111099 -0.510307  1.303631
2332  6.917349  0.071724 -0.515540  1.275094
2333  6.876178  0.256766 -0.506626  1.414609
2334  6.990121  0.107235 -0.498072  1.408268
2335  7.006254  0.188936 -0.509502  1.408268
2336  7.018641  0.249687 -0.502748  1.401926
2337  7.006432  0.289742 -0.508379  1.376560
2338  6.977877  0.058189 -0.543319  1.316314
2339  6.914126  0.237597 -0.554390  1.287777
2340  6.801546  0.232787 -0.589901  1.249727
2341  6.689293  0.240207 -0.630100  1.268752
2342  6.747357  0.250768 -0.601728  1.195824

[2343 rows x 4 columns]

In [17]:
from sklearn.externals import joblib
model = LogisticRegression().fit(X_train, y_train)



filename = '/tmp/CJ_classifier.joblib.pkl'
_ = joblib.dump(model, filename, compress=9)

model2 = joblib.load(filename)
model2

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [79]:
a=X_train.iloc[1,:]
a=pd.DataFrame(a)
b=a.T
model.predict(b)

In [18]:
c

NameError: name 'c' is not defined

In [20]:
c=list([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,
        29,30,31,32,33,34,35,36,37,38,39])
c=pd.DataFrame(c)

In [33]:
import numpy as np
e=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,
        29,30,31,32,33,34,35,36,37,38,39])
e=pd.DataFrame(e)
F=e.T

In [34]:
filename = '/tmp/CJ_classifier.joblib.pkl'
#_ = joblib.dump(model, filename, compress=9)
from sklearn.externals import joblib
model2 = joblib.load(filename)
model2

h=model2.predict(F)

array([0], dtype=int64)

In [46]:
h=model2.predict(F)
h=list(h)
k=h[0]
k=str(k)
k

'0'

In [25]:
from sklearn.model_selection import train_test_split
df=pd.read_csv('오뚜기국내PCA최종본.csv',engine='python')
df.iloc[:,:3]

pc1       pc2       pc3
0    -8.076955 -4.332277 -7.047220
1    -8.013912 -4.470804 -7.005688
2    -8.006509 -4.515060 -6.972148
3    -7.795684 -4.518484 -6.930466
4    -7.711748 -4.799284 -6.832768
5    -7.654417 -4.919061 -6.784022
6    -7.557367 -4.983991 -6.730631
7    -7.409448 -5.087126 -6.681922
8    -7.342716 -5.143531 -6.594702
9    -7.401306 -5.321472 -6.609845
10   -7.266494 -5.290721 -6.558619
11   -7.206541 -5.311598 -6.499400
12   -7.218656 -5.292112 -6.511370
13   -7.320143 -5.141982 -6.556466
14   -7.263473 -5.133394 -6.524091
15   -7.265249 -5.199208 -6.530555
16   -7.184006 -5.178355 -6.462469
17   -7.188520 -5.335917 -6.433696
18   -7.009819 -5.379576 -5.268778
19   -7.063324 -5.289298 -5.255334
20   -7.014371 -5.292668 -5.232298
21   -6.984467 -5.353756 -5.192453
22   -6.993107 -5.175175 -5.203250
23   -6.905810 -5.247276 -5.152870
24   -6.859810 -5.327160 -5.131031
25   -6.822667 -5.473029 -5.128510
26   -6.695660 -5.447327 -5.066030
27   -6.590729 -5.563797 -5.035370
28   -6.510929 -5.771331 -4.978384
29   -6.594985 -5.746497 -4.963119
...        ...       ...       ...
2313  6.587209  0.625727  0.012249
2314  6.487272  0.631309 -0.014351
2315  6.517806  0.646833 -0.003893
2316  6.520349  0.620973  0.009595
2317  6.545051  0.651869  0.025649
2318  6.545144  0.679142  0.021467
2319  6.536440  0.627427  0.014413
2320  6.592440  0.533744  0.007608
2321  6.628014  0.604037  0.003333
2322  6.667528  0.588465  0.020132
2323  6.681253  0.637817  0.022389
2324  6.661373  0.647080  0.020322
2325  6.652743  0.677344  0.019089
2326  6.613715  0.657049  0.013381
2327  6.677021  0.664219  0.028787
2328  6.670241  0.638609  0.008725
2329  6.553240  0.350158 -0.549213
2330  6.657457  0.067841 -0.531551
2331  6.810934 -0.111099 -0.510307
2332  6.917349  0.071724 -0.515540
2333  6.876178  0.256766 -0.506626
2334  6.990121  0.107235 -0.498072
2335  7.006254  0.188936 -0.509502
2336  7.018641  0.249687 -0.502748
2337  7.006432  0.289742 -0.508379
2338  6.977877  0.058189 -0.543319
2339  6.914126  0.237597 -0.554390
2340  6.801546  0.232787 -0.589901
2341  6.689293  0.240207 -0.630100
2342  6.747357  0.250768 -0.601728

[2343 rows x 3 columns]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:3], df["close"], test_size=0.33, random_state=42)

In [32]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import r2_score

from sklearn.linear_model import ElasticNet
alpha = 0.1
enet = ElasticNet(alpha=alpha, l1_ratio=0.7)

y_pred_enet = enet.fit(X_train, y_train).predict(X_test)
r2_score_enet = r2_score(y_test, y_pred_enet)
r2_score_enet

0.9206898294538876

In [34]:
# Performing Grid Search specific alpha values for ElasticNet
#alphas = np.array([1,0.1,0.01,0.001,0.0001])
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform as sp_rand
from sklearn.model_selection import RandomizedSearchCV
alphas = np.logspace(-6, 6, 100)

# param_grid = {'alpha': sp_rand(), 'l1_ratio': sp_rand()}
model4 = ElasticNet()
grid_ELN = GridSearchCV(estimator=model4,cv = 10, param_grid=dict(alpha=alphas))
# rsearch = RandomizedSearchCV(estimator=model, param_distributions=param_grid, n_iter=100)
grid_ELN.fit(X_train, y_train)
print(grid_ELN)
# summarize the results of the grid search
print(grid_ELN.best_score_)
print(grid_ELN.best_estimator_.alpha)

GridSearchCV(cv=10, error_score='raise',
       estimator=ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': array([1.00000e-06, 1.32194e-06, ..., 7.56463e+05, 1.00000e+06])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)
0.9180315931684208
0.017475284000076828


In [36]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_test,grid_ELN.predict(X_test)))

0.2793491619126774

In [37]:
# Performing Grid Search with specific alpha values for Ridge
#alphas = np.array([1,0.1,0.01,0.001,0.0001])
alphas = np.logspace(-6, 6, 100)
model2 = Ridge()
grid_Ridge = GridSearchCV(model2, cv = 10,  param_grid = dict(alpha=alphas), scoring = 'r2')
grid_Ridge.fit(X_train, y_train)
print(grid_Ridge)
# summarize the results of the grid search
print(grid_Ridge.best_score_)
print(grid_Ridge.best_estimator_.alpha)

np.sqrt(mean_squared_error(y_test,grid_Ridge.predict(X_test)))

GridSearchCV(cv=10, error_score='raise',
       estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': array([1.00000e-06, 1.32194e-06, ..., 7.56463e+05, 1.00000e+06])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='r2', verbose=0)
0.918008691780945
100.0


0.2793003977978205

In [38]:
# Performing Grid Search with specific alpha values for Ridge
#alphas = np.array([1,0.1,0.01,0.001,0.0001])
alphas = np.logspace(-6, 6, 100)
model2 = Lasso()
grid_Lasso = GridSearchCV(model2, cv = 10,  param_grid = dict(alpha=alphas), scoring = 'r2')
grid_Lasso.fit(X_train, y_train)
print(grid_Lasso)
# summarize the results of the grid search
print(grid_Lasso.best_score_)
print(grid_Lasso.best_estimator_.alpha)

np.sqrt(mean_squared_error(y_test,grid_Lasso.predict(X_test)))

GridSearchCV(cv=10, error_score='raise',
       estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': array([1.00000e-06, 1.32194e-06, ..., 7.56463e+05, 1.00000e+06])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='r2', verbose=0)
0.9180364634137866
0.01


0.27934250243504893

In [23]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state = 1)
clf.fit(X_train, y_train)
clf.score(X_test,y_test)

0.8354632587859425

In [31]:
from sklearn import model_selection
from sklearn.model_selection import cross_val_score
kfold = model_selection.KFold(n_splits=10, random_state=7)
modelCV = LogisticRegression()
scoring = 'accuracy'
results = model_selection.cross_val_score(modelCV, X_train, y_train, cv=kfold, scoring=scoring)
print("10-fold cross validation average accuracy: %.3f" % (results.mean()))

10-fold cross validation average accuracy: 0.825


In [35]:
y_pred = clf.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(clf.score(X_test, y_test)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

Accuracy of logistic regression classifier on test set: 0.84
[[280  48]
 [ 55 243]]


In [ ]:
from sklearn.externals import joblib
model = LogisticRegression().fit(X_train, y_train)



filename = '/CJ_classifier.joblib.pkl'
_ = joblib.dump(model, filename, compress=9)

model2 = joblib.load(filename)
model2